version: "3.9"
services:
  app:
    image: 0utercore/delta:${TAG:-"latest"}
    ports:
      - "${APP_PORT:-1414}:1414"
    environment:
      - NODE_NAME=${NODE_NAME:-"delta-node"}
      - NODE_DESCRIPTION=${NODE_DESCRIPTION:-"Delta Node"}
      - NODE_TYPE=${NODE_TYPE:-"delta"}
      - MODE=${MODE:-"cluster"}
      - DB_DSN=${DB_DSN:-"delta.db"}
      - DELTA_AUTH=${DELTA_AUTH:-""}
      - MAX_CLEANUP_WORKERS=${MAX_CLEANUP_WORKERS:-1500}